import time
from backend.utils.gemini_client import get_gemini_text_model
from backend.utils.logger import get_logger
from backend.config import settings

logger = get_logger(__name__)

_SYSTEM_PROMPT = """You are a professional, empathetic customer support agent for an e-commerce company.
Write a reply to the customer's support message.

Rules:
- Be warm, concise, and professional (2-4 sentences)
- Acknowledge the specific problem the customer mentioned
- State the next concrete action you will take
- Do NOT use generic filler like "I understand your frustration" as the first sentence
- Do NOT include a subject line
- Do NOT sign off with a name
- Return ONLY the reply text, no JSON, no markdown"""


def generate_suggested_reply(message: str, category: str | None = None) -> dict:
    """
    Generate a professional, empathetic agent reply for a support ticket.
    Called on-demand (not during batch pipeline) to keep batch costs low.
    """
    context = f"[Category: {category}]\n\n" if category else ""
    user_prompt = f"{context}Customer message:\n\"{message[:1000]}\""

    model = get_gemini_text_model()

    for attempt in range(settings.MAX_RETRIES):
        try:
            response = model.generate_content(
                [{"role": "user", "parts": [_SYSTEM_PROMPT + "\n\n" + user_prompt]}]
            )
            reply = response.text.strip()
            return {
                "reply": reply,
                "note": f"Generated by {settings.GEMINI_MODEL}",
            }
        except Exception as exc:
            wait = 2 ** attempt
            logger.warning(
                f"Responder attempt {attempt + 1} failed: {exc}. Retrying in {wait}s..."
            )
            time.sleep(wait)

    logger.error("Responder: all retries exhausted — returning fallback reply.")
    return {
        "reply": (
            "Thank you for contacting us. We have received your message and a member "
            "of our support team will follow up with you within 24 hours."
        ),
        "note": "Fallback reply — Gemini unavailable.",
    }
